DATA:
  AUGMENT: 0
  CLASS_NAME_FILE: 'configs/namefiles/coco-91.names'

DETECTOR:
  NAME: ["SSD"] # 'SSDlite',"FASTER_RCNN", "SSD"
  INPUT_SIZE: [352, 640] # height, width
  BATCH_SIZE: 1
  CONF_THRESH: 0.6
  IOU_THRESH: 0.45
  PERTURB:
    GATE: null

ATTACKER:
  METHOD: ""
  EPSILON: # 0-255
  MAX_EPOCH:
  ITER_STEP:
  STEP_LR:
  TARGET_CLASS:
  ATTACK_CLASS: '11' # -1 attack all classes, or you can select the class id
  LOSS_FUNC: ''
  PATCH:
    WIDTH: 640
    HEIGHT: 224